# General Jekyll Config
url: https://deepaksrivastav.github.io/
lsi: false
excerpt_separator: ""
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
